version: "3.8"
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.47.0
    ports:
      - '8428:8428'
    volumes:
      - 'vm-data:/victoria-metrics-data'

  prometheus:
    image: prom/prometheus:v2.22.2
    ports:
      - '9090:9090'
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.3.3
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-data:/usr/local/var/lib/grafana'

  cadvisor:
    image: google/cadvisor:v0.33.0
    ports:
      - '8098:8098'
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    privileged: true
    command:
      - '-port=8098'

volumes:
  vm-data:
  grafana-data:
