global:
  scrape_interval: 5s
  external_labels:
    noc: local-prometheus

remote_write:
  - url: http://victoriametrics:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

scrape_configs:
  - job_name: default
    static_configs:
      - targets:
        - 'victoriametrics:8428'
        - 'grafana:3000'
        - 'prometheus:9090'
        - 'cadvisor:8098'
